version: "3.8"

x-build: &dockerfile-dev-build
  context: .
  dockerfile: Dockerfile.dev

services:
  db:
    image: postgres:13.2-alpine
    # "root" execution of the PostgreSQL server is not permitted.
    user: postgres
    environment:
      POSTGRES_USER: boss_role
      POSTGRES_PASSWORD: boss_password
    volumes:
      - ./scripts/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
    - "5432:5432"
  remote-interpreter:
    build: *dockerfile-dev-build
    volumes:
      - .:/app
    env_file: .env.development
    ports:
      - "8000:8000"
    depends_on:
      - db
    command:
      [
        "./scripts/wait-for-it.sh",
        "db:5432",
        "-t",
        "120",
        "--",
        "./scripts/start-development.sh",
      ]
  jafar-app:
    build: *dockerfile-dev-build
    volumes:
      - .:/app
    env_file: .env.development
    environment:
      DB_SCHEMA: jafar_dev
      DB_USER: role_jafar_dev
    ports:
      - "8001:8000"
    depends_on:
      - db
    command:
      [
        "./scripts/wait-for-it.sh",
        "db:5432",
        "-t",
        "120",
        "--",
        "./scripts/start-development.sh",
      ]
  iago-app:
    build: *dockerfile-dev-build
    volumes:
      - .:/app
    env_file: .env.development
    environment:
      DB_SCHEMA: iago_dev
      DB_USER: role_iago_dev
    ports:
      - "8002:8000"
    depends_on:
      - db
    command:
      [
        "./scripts/wait-for-it.sh",
        "db:5432",
        "-t",
        "120",
        "--",
        "./scripts/start-development.sh",
      ]
  jasmine-app:
    build: *dockerfile-dev-build
    volumes:
      - .:/app
    env_file: .env.development
    environment:
      DB_SCHEMA: jasmine_dev
      DB_USER: role_jasmine_dev
    ports:
      - "8003:8000"
    depends_on:
      - db
    command:
      [
        "./scripts/wait-for-it.sh",
        "db:5432",
        "-t",
        "120",
        "--",
        "./scripts/start-development.sh",
      ]
  tests:
    build: *dockerfile-dev-build
    volumes:
      - .:/app
    env_file: .env.development
    depends_on:
      - db
    command:
      [
        "./scripts/wait-for-it.sh",
        "db:5432",
        "-t",
        "120",
        "--",
        "./scripts/start-tests.sh",
      ]
  lint:
    build: *dockerfile-dev-build
    volumes:
      - .:/app
    command: ["./scripts/start-lint.sh"]
  formatter:
    build: *dockerfile-dev-build
    volumes:
      - .:/app
    command: ["./scripts/start-formatter.sh"]
